using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ems.sales.Models
{
    public class MdlSmrTrnProformaInvoice : result
    {
        public List<proformainvoicesummary_list> proformainvoicesummary_list {  get; set; }
        public List<proformainvoicelist> proformainvoicelist {  get; set; }
        public List<ProformaInvoiceEditlist> ProformaInvoiceEditlist {  get; set; }
        public List<Proformainvoiceproductsubmit_list> Proformainvoiceproductsubmit_list {  get; set; }
        public List<GetOrderToProformaInvoiceProduct_list> GetOrderToProformaInvoiceProduct_list {  get; set; }
        public List<ProformaInvoiceProductlist> ProformaInvoice_Productlist {  get; set; }
        public double grand_total { get; set; }
    }
    public class ProformaInvoiceProductlist : result
    {
        public string salesorder_gid { get; set; }
        public string currency_code { get; set; }
        public string branch_name { get; set; }
        public string invoice_date { get; set; }
        public string salesorder_date { get; set; }
        public string salesorderdtl_gid { get; set; }
        public string so_referenceno1 { get; set; }
        public string product_name { get; set; }
        public string productgroup_name { get; set; }
        public string user_firstname { get; set; }
        public string start_date { get; set; }
        public string end_date { get; set; }
        public string so_referencenumber { get; set; }
        public string payment_terms { get; set; }
        public string freight_terms { get; set; }
        public string tax_name3 { get; set; }
        public string tax1_gid { get; set; }
        public string tax2_gid { get; set; }
        public string tax3_gid { get; set; }
        public string tax_percentage { get; set; }
        public string tax_percentage2 { get; set; }
        public string tax_percentage3 { get; set; }
        public string customer_gid { get; set; }
        public string product_remarks { get; set; }
        public string customer_name { get; set; }
        public string customer_contact_person { get; set; }
        public string mobile { get; set; }
        public string customer_email { get; set; }
        public string customer_address { get; set; }
        public string product_gid { get; set; }
        public string product_price { get; set; }
        public string display_field { get; set; }
        public string tax_amount1 { get; set; }
        public string qty_quoted { get; set; }
        public string margin_percentage { get; set; }
        public string margin_amount { get; set; }
        public string tax_name { get; set; }
        public string tax_amount { get; set; }
        public string tax_name2 { get; set; }
        public string tax_amount2 { get; set; }
        public string total_amount { get; set; }
        public string gst_amount { get; set; }
        public string final_amount { get; set; }
        public string product_description { get; set; }
        public string addon_charge { get; set; }
        public string additional_discount { get; set; }
        public string freight_charges { get; set; }
        public string buyback_charges { get; set; }
        public string packing_charges { get; set; }
        public string insurance_charges { get; set; }
        public string roundoff { get; set; }
        public string total_price { get; set; }
        public string Grandtotal { get; set; }
        public string advance_roundoff { get; set; }
        public string termsandconditions { get; set; }
        public string customercontact_name { get; set; }
        public string exchange_rate { get; set; }
        public string product_code { get; set; }
        public string productuom_name { get; set; }
        public string vendor_price { get; set; }
        public string qty_invoice { get; set; }
        public string total { get; set; }
        public string tax_amount3 { get; set; }
        public string vendor_companyname { get; set; }
        public string productuom_gid { get; set; }
        public string product_discount_percentage { get; set; }
        public string product_discount_amount { get; set; }
        public string price { get; set; }
        public string product_price1 { get; set; }
        public string net_amount { get; set; }
        public string total_tax_amount { get; set; }
        public string totalprice { get; set; }
        public string cost_price { get; set; }
    }
    public class GetOrderToProformaInvoiceProduct_list : result
    {
        public string invoice_gid { get; set; }
        public string invoicedtl_gid { get; set; }
        public string customerproduct_code { get; set; }
        public string product_gid { get; set; }
        public string tax1_gid { get; set; }
        public string tax2_gid { get; set; }
        public string tax3_gid { get; set; }
        public string qty_quoted { get; set; }
        public string uom_gid { get; set; }
        public string product_total { get; set; }
        public string productprice { get; set; }
        public string tax_amount1 { get; set; }
        public string tax_amount2 { get; set; }
        public string tax_amount3 { get; set; }
        public string total_amount { get; set; }
        public string productgroup_gid { get; set; }
        public string productgroup_name { get; set; }
        public string product_code { get; set; }
        public string product_remarks { get; set; }
        public string tax_name1 { get; set; }
        public string tax_name2 { get; set; }
        public string tax_name3 { get; set; }
        public string discount_amount { get; set; }
        public string margin_percentage { get; set; }
        public string discount_percentage { get; set; }
        public string product_name { get; set; }
        public string taxsegment_gid { get; set; }
        public string tax_percentage { get; set; }
        public string tax_percentage2 { get; set; }
        public string tax_percentage3 { get; set; }
        public string uom_name { get; set; }
        public string taxamount { get; set; }
        public string display_field { get; set; }
    }
    public class Proformainvoiceproductsubmit_list
    {
        public string taxsegment_gid { get; set; }
        public string taxseg_taxtotal { get; set; }
        public string taxsegmenttax_gid { get; set; }
        public string qty_requested { get; set; }
        public double productquantity { get; set; }
        public string discountprecentage { get; set; }
        public string invoice_gid { get; set; }
        public double discount_amount { get; set; }
        public string tax1 { get; set; }
        public string tax2 { get; set; }
        public string taxamount2 { get; set; }
        public string taxamount1 { get; set; }
        public string producttotal_amount { get; set; }
        public string product_name { get; set; }
        public string product_gid { get; set; }
        public string productuom_gid { get; set; }
        public string productuom_name { get; set; }
        public string productgroup_gid { get; set; }
        public string productgroup_name { get; set; }
        public string product_code { get; set; }
        public double unitprice { get; set; }
        public string display_field { get; set; }
        public string tax3 { get; set; }
        public bool status { get; set; }
        public string message { get; set; }
        public string cost_price { get; set; }
        public string discountpercentage { get; set; }
        public string discountamount { get; set; }
        public string taxamount3 { get; set; }
        public string taxgid1 { get; set; }
        public string taxgid2 { get; set; }
        public string taxgid3 { get; set; }
        public string taxprecentage1 { get; set; }
        public string taxprecentage2 { get; set; }
        public string taxprecentage3 { get; set; }
        public string taxname1 { get; set; }
        public string taxname2 { get; set; }
        public string taxname3 { get; set; }
        public string product_desc { get; set; }
        public string tax_prefix { get; set; }
        public string tax_prefix2 { get; set; }
        public string tax_prefix3 { get; set; }
    }
    public class ProformaInvoiceEditlist : result
    {
        public string salesorder_gid { get; set; }
        public string invoice_referenceno { get; set; }
        public string advance_amount { get; set; }
        public string invoice_termsandconditions { get; set; }
        public string email_address { get; set; }
        public string contact_person { get; set; }
        public string contact_no { get; set; }
        public string invoice_address { get; set; }
        public string invoice_roundoff { get; set; }
        public string invoice_advance_amount { get; set; }
        public string invoice_gid { get; set; }
        public string invoice_refno { get; set; }
        public string invoice_date { get; set; }
        public string payment_term { get; set; }
        public string payment_date { get; set; }
        public string so_referenceno1 { get; set; }
        public string total_price { get; set; }
        public string gst_amount { get; set; }
        public string total_amount { get; set; }
        public string termsandconditions { get; set; }
        public string user_firstname { get; set; }
        public string additionalcharges_amount { get; set; }
        public string tax_amount { get; set; }
        public string total_tax_amount { get; set; }
        public string invoice_amount { get; set; }
        public string customer_name { get; set; }
        public string customer_contactperson { get; set; }
        public string customer_email { get; set; }
        public string customer_address { get; set; }
        public string invoice_percent { get; set; }
        public string branch_name { get; set; }
        public string so_referencenumber { get; set; }
        public string freight_terms { get; set; }
        public string end_date { get; set; }
        public string start_date { get; set; }
        public string payment_terms { get; set; }
        public string mobile { get; set; }
        public string currency_code { get; set; }
        public string exchange_rate { get; set; }
        public string invoice_remarks { get; set; }
        public string roundoff { get; set; }
        public string freight_charges { get; set; }
        public string addon_charge { get; set; }
        public string buyback_charges { get; set; }
        public string packing_charges { get; set; }
        public string insurance_charges { get; set; }
        public string advanceroundoff { get; set; }
        public string invoicepercent_amount { get; set; }
        public string invoicedtl_gid { get; set; }
        public string qty_invoice { get; set; }
        public string product_price { get; set; }
        public string product_price1 { get; set; }
        public string customerproduct_code { get; set; }
        public string discount_amount1 { get; set; }
        public string discount_amount { get; set; }
        public string salestype_name { get; set; }
        public string discount_percentage { get; set; }
        public string tax_amount2 { get; set; }
        public string tax_amount3 { get; set; }
        public string tax_name { get; set; }
        public string tax_name2 { get; set; }
        public string tax_name3 { get; set; }
        public string vendor_price { get; set; }
        public string price { get; set; }
        public string display_field { get; set; }
        public string product_gid { get; set; }
        public string product_code { get; set; }
        public string product_name { get; set; }
        public string productgroup_gid { get; set; }
        public string productgroup_name { get; set; }
        public string productuom_name { get; set; }
        public string uom_gid { get; set; }
        public string mode_of_despatch { get; set; }
        public string freight { get; set; }
        public string ship_to { get; set; }
        public string sales_type { get; set; }
        public string tax_name4 { get; set; }
        public string tax_amount4 { get; set; }
        public string billing_email { get; set; }
        public string currency_gid { get; set; }
        public string branch_gid { get; set; }
        public string cost_price { get; set; }
        public string product_total { get; set; }
        public string due_date   { get; set; }
        public string bill_email { get; set; }
        public string shipping_to { get; set; }
        public string dispatch_mode { get; set; }
        public string proforma_advance_roundoff { get; set; }
        public string additional_discount { get; set; }
        public string grandtotal { get; set; }
        public string proforma_remarks { get; set; }
        public string gst_number { get; set; }
        public string proforma_advance_amount { get; set; }
        public string customer_mobile { get; set; }
        public string customercontact_names { get; set; }
        public string totalamount { get; set; }
        public string customer_gid { get; set; }
        public string payment_days { get; set; }
        public string delivery_days { get; set; }
        public string edit_proforma_invoice_advance_percentage { get; set; }
        public string code { get; set; }
        public string currencyexchange_gid { get; set; }
    }
    public class proformainvoicelist : result
    {
        public string salesorder_gid { get; set; }
        public string branch_gid { get; set; }
        public string customer_gid { get; set; }
        public string payment_terms { get; set; }
        public string employee_gid { get; set; }
        public string proforma_so_ref_no { get; set; }
        public string proforma_invoice_refno { get; set; }
        public string invoice_date { get; set; }
        public string due_date { get; set; }
        public string additionaltaxamount { get; set; }
        public string proforma_maximum_addon_amount { get; set; }
        public string additional_discount { get; set; }
        public string grandtotal { get; set; }
        public string invoiceamount { get; set; }
        public string created_date { get; set; }
        public string proforma_customer_name { get; set; }
        public string customer_mobile { get; set; }
        public string customercontact_names { get; set; }
        public string proforma_advance_amount { get; set; }
        public string invoicestatus { get; set; }
        public string proforma_remarks { get; set; }
        public string proforma_termsandconditions { get; set; }
        public string currency_code { get; set; }
        public string exchange_rate { get; set; }
        public string totalamount_L { get; set; }
        public string invoiceamount_L { get; set; }
        public string additionalchargesamount_L { get; set; }
        public string discountamount_L { get; set; }
        public string customer_address { get; set; }
        public string termsandconditions { get; set; }
        public string invoiceflag { get; set; }
        public string customer_email { get; set; }
        public string proforma_advance_roundoff { get; set; }
        public string invoicepercent { get; set; }
        public string invoicepercentamount { get; set; }
        public string invoicefrom { get; set; }
        public string roundoff { get; set; }
        public string dispatch_mode { get; set; }
        public string freight_terms { get; set; }
        public string shipping_to { get; set; }
        public string sales_type { get; set; }
        public string bill_email { get; set; }
        public string freight_charges { get; set; }
        public string totalamount { get; set; }
        public string addon_charge { get; set; }
        public string tax_name4 { get; set; }
        public string tax_amount4 { get; set; }
        public string proforma_buy_back_scrap_charges { get; set; }
        public string proforma_packing_forwarding_charges { get; set; }
        public string proforma_insurance_charges { get; set; }
    }
    public class proformainvoicesummary_list : result
    {
        public string currency { get; set; }
        public string invoice_reference { get; set; }
        public string invoice_refno { get; set; }
        public string invoice_date { get; set; }
        public string so_referencenumber { get; set; }
        public string customer_name { get; set; }
        public string customer_contactperson { get; set; }
        public string mobile { get; set; }
        public string details { get; set; }
        public string invoice_from { get; set; }
        public string mail_status { get; set; }
        public string invoice_amount { get; set; }
        public string overall_status { get; set; }
        public string invoice_gid { get; set; }
    }
}